[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.2"
ed25519-dalek = "1.0.1"
rand = "0.7"
zeroize = "1.3.0"
base64 = "0.13.0"
